- id: pubmed:32580634
  image: https://www.ahajournals.org/cms/asset/34b376bb-9f2e-4de7-a42e-b6ef03836154/atvb.2020.40.issue-8.cover.gif

- id: pubmed:33119549
  image: https://df6sxcketz7bb.cloudfront.net/volumes/5/23/5-23-cover.jpg

- id: pubmed:33989378
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/cardiovascres/PAP/10.1093_cvr_cvab174/2/m_cvab174f3.jpeg?Expires=1639591991&Signature=F23kFDx6FMeXsz7Ja8OjHC66P07HLb2~dbO7x~9GyiYQcFUGdnVGeo24VduhqXyNzxL0YfAzZyAVZncwByjknrbIahC~RPDwBKECa4LS9x~LqzBZOSSXOkAvCEpkltL1qbW1RySmSWwFkbfqTmKha2q1wVkGMEvVS6WkPjco55IZpZlBXJlLf6BAde8uC~X42rgnl1oc9aGE7Clw~9hts1P6TbBvn7IVEHd72XOfvN75oDDnJwanGGPIJ88-WUNO3SFmvUTba4r8lpCmH~PHX1AY38VdEKg-kx6u~2z-0Pb9vZtTNnaB5EJa4YG0YRCsN2qZ8T~raQyX9OmRIkfQCQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
- id: pubmed:27834190
  image: https://www.ahajournals.org/cms/asset/84ac3a37-08f1-448e-b05b-0c74b8f104c2/res.2017.120.issue-2.cover.gif
